/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmyshow;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaydip
 */

public class MainBookingWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainBookingWindow
     */
    int seatPrice=0,foodPrice=0,food=0,seatno=0;
    static String getmovie,getseat,getfood;
    float total=0.f;
    public MainBookingWindow(String getmovie1,String getseat1,String getfood1,int food1,int seatno1,float total1) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1920, 1080);
        
        
        seatType_combo.setEnabled(false);
        seatNo_combo.setEnabled(false);
        food_combo.setEnabled(false);
        foodNo_combo.setEnabled(false);
        
        getmovie=getmovie1;
        getseat=getseat1;
        getfood=getfood1;
        food=food1;
        seatno=seatno1;
        total=total1;
        
    }
    
    void selectionOfSeat()
    {
        if(seatType_combo.getSelectedItem().equals("Select Seat Type"))
        {
            seatNo_combo.setEnabled(false);
            food_combo.setEnabled(false);
            foodNo_combo.setEnabled(false);
            seatType_label.setText("");
        }
        else if(seatType_combo.getSelectedItem().equals("Platinum - Rs.200"))
        {
            seatType_label.setText("Rs.200");
            seatNo_combo.setEnabled(true);
            seatNo_combo.setSelectedItem("Select No. Of Seats");
            seatNo_label.setText("");
            getseat=seatType_combo.getSelectedItem().toString();
            
        }
        else if(seatType_combo.getSelectedItem().equals("Diamond - Rs.150"))
        {
            seatType_label.setText("Rs.150");
            seatNo_combo.setEnabled(true);
            seatNo_combo.setSelectedItem("Select No. Of Seats");
            seatNo_label.setText("");
            getseat=seatType_combo.getSelectedItem().toString();
        }
        else if(seatType_combo.getSelectedItem().equals("Gold - Rs.100"))
        {
            seatType_label.setText("Rs.100");
            seatNo_combo.setEnabled(true);
            seatNo_combo.setSelectedItem("Select No. Of Seats");
            seatNo_label.setText("");
            getseat=seatType_combo.getSelectedItem().toString();
        }
        else if(seatType_combo.getSelectedItem().equals("Silver - Rs.70"))
        {
            seatType_label.setText("Rs.70");
            seatNo_combo.setEnabled(true);
            seatNo_combo.setSelectedItem("Select No. Of Seats");
            seatNo_label.setText("");
            getseat=seatType_combo.getSelectedItem().toString();
        }
        
    }
    
    void newButton()
    {
        gst_label.setText("");
        grossAmount_label.setText("");
        label1.setEnabled(true);
        idiot_label.setEnabled(true);
        rockstar_label.setEnabled(true);
        bhagtosKayMujaraKar_label.setEnabled(true);
        seatType_combo.setEnabled(false);
        seatNo_combo.setEnabled(false);
        food_combo.setEnabled(false);
        foodNo_combo.setEnabled(false);
        seatType_label.setText("");
        seatNo_label.setText("");
        food_label.setText("");
        foodNo_label.setText("");
        
        seatType_combo.setSelectedItem("Select Seat Type");
        seatNo_combo.setSelectedItem("Select No. Of Seats");
        food_combo.setSelectedItem("Select Food & Beverage");
        foodNo_combo.setSelectedItem("Select Food & Beverage Quantity");
    }
    void gstAndGrossAmount()
    {
        float gst=((foodPrice+(float)seatPrice)*18)/100;
        gst_label.setText("Rs."+gst);
        total=foodPrice+seatPrice+gst;
        grossAmount_label.setText("Rs."+total);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        idiot_label = new javax.swing.JLabel();
        rockstar_label = new javax.swing.JLabel();
        bhagtosKayMujaraKar_label = new javax.swing.JLabel();
        seatType_combo = new javax.swing.JComboBox<>();
        seatNo_combo = new javax.swing.JComboBox<>();
        food_combo = new javax.swing.JComboBox<>();
        foodNo_combo = new javax.swing.JComboBox<>();
        seatType_label = new javax.swing.JLabel();
        seatNo_label = new javax.swing.JLabel();
        food_label = new javax.swing.JLabel();
        foodNo_label = new javax.swing.JLabel();
        gst_label = new javax.swing.JLabel();
        grossAmount_label = new javax.swing.JLabel();
        new_button = new javax.swing.JButton();
        payment_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Your Show");
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/zindagi-na-milegi-dobara.jpg"))); // NOI18N
        label1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                label1MouseMoved(evt);
            }
        });
        label1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                label1FocusGained(evt);
            }
        });
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });
        getContentPane().add(label1);
        label1.setBounds(837, 30, 220, 316);

        idiot_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/220px-3_idiots_poster.jpg"))); // NOI18N
        idiot_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                idiot_labelMouseMoved(evt);
            }
        });
        idiot_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiot_labelMouseClicked(evt);
            }
        });
        getContentPane().add(idiot_label);
        idiot_label.setBounds(1107, 30, 220, 316);

        rockstar_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/rockstar movie poster.jpg"))); // NOI18N
        rockstar_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rockstar_labelMouseMoved(evt);
            }
        });
        rockstar_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rockstar_labelMouseClicked(evt);
            }
        });
        getContentPane().add(rockstar_label);
        rockstar_label.setBounds(1377, 30, 220, 316);

        bhagtosKayMujaraKar_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/Bhagtos kay mujara kar.jpg"))); // NOI18N
        bhagtosKayMujaraKar_label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bhagtosKayMujaraKar_labelMouseMoved(evt);
            }
        });
        bhagtosKayMujaraKar_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bhagtosKayMujaraKar_labelMouseClicked(evt);
            }
        });
        getContentPane().add(bhagtosKayMujaraKar_label);
        bhagtosKayMujaraKar_label.setBounds(1647, 30, 220, 316);

        seatType_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seatType_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Seat Type", "Platinum - Rs.200", "Diamond - Rs.150", "Gold - Rs.100", "Silver - Rs.70" }));
        seatType_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatType_comboActionPerformed(evt);
            }
        });
        getContentPane().add(seatType_combo);
        seatType_combo.setBounds(837, 389, 592, 45);

        seatNo_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seatNo_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select No. Of Seats", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        seatNo_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatNo_comboActionPerformed(evt);
            }
        });
        getContentPane().add(seatNo_combo);
        seatNo_combo.setBounds(837, 469, 592, 45);

        food_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        food_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Food & Beverage", "Samosa - Rs.100", "PopCorn - Rs.150", "Coke - Rs.160", "Samosa Coke Combo - Rs.260", "Samosa PopCorn Combo - Rs.250" }));
        food_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_comboActionPerformed(evt);
            }
        });
        getContentPane().add(food_combo);
        food_combo.setBounds(837, 549, 592, 45);

        foodNo_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        foodNo_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Food & Beverage Quantity", "1", "2", "3", "4" }));
        foodNo_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodNo_comboActionPerformed(evt);
            }
        });
        getContentPane().add(foodNo_combo);
        foodNo_combo.setBounds(837, 629, 592, 45);

        seatType_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seatType_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(seatType_label);
        seatType_label.setBounds(1719, 389, 148, 45);

        seatNo_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seatNo_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(seatNo_label);
        seatNo_label.setBounds(1719, 469, 148, 45);

        food_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        food_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(food_label);
        food_label.setBounds(1719, 549, 148, 45);

        foodNo_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        foodNo_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(foodNo_label);
        foodNo_label.setBounds(1719, 629, 148, 45);

        gst_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gst_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(gst_label);
        gst_label.setBounds(1719, 709, 148, 45);

        grossAmount_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grossAmount_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(grossAmount_label);
        grossAmount_label.setBounds(1719, 789, 148, 45);

        new_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_button.setText("New");
        new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(new_button);
        new_button.setBounds(837, 869, 277, 51);

        payment_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        payment_button.setText("Proceed To Payment");
        payment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(payment_button);
        payment_button.setBounds(1215, 869, 322, 51);

        cancel_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel_button.setText("Cancel Order");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);
        cancel_button.setBounds(1619, 869, 248, 51);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Gross Amount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1552, 789, 149, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("GST 18%");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1555, 709, 149, 45);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmyshow/background label 2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1960, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatType_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatType_comboActionPerformed
        // TODO add your handling code here:
        selectionOfSeat();
    }//GEN-LAST:event_seatType_comboActionPerformed

    private void label1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label1FocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_label1FocusGained

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        label1.setEnabled(true);
        idiot_label.setEnabled(false);
        rockstar_label.setEnabled(false);
        bhagtosKayMujaraKar_label.setEnabled(false);
        seatType_combo.setEnabled(true);
        getmovie="Zindagi Na Milegi Dobara";
    }//GEN-LAST:event_label1MouseClicked

    private void idiot_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiot_labelMouseClicked
        // TODO add your handling code here:
        idiot_label.setEnabled(true);
        label1.setEnabled(false);
        rockstar_label.setEnabled(false);
        bhagtosKayMujaraKar_label.setEnabled(false);
        seatType_combo.setEnabled(true);
        getmovie="3 Idiot";
    }//GEN-LAST:event_idiot_labelMouseClicked

    private void rockstar_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockstar_labelMouseClicked
        // TODO add your handling code here:
        rockstar_label.setEnabled(true);
        label1.setEnabled(false);
        idiot_label.setEnabled(false);
        bhagtosKayMujaraKar_label.setEnabled(false);
        seatType_combo.setEnabled(true);
        getmovie="Rockstar";
    }//GEN-LAST:event_rockstar_labelMouseClicked

    private void bhagtosKayMujaraKar_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhagtosKayMujaraKar_labelMouseClicked
        // TODO add your handling code here:
        rockstar_label.setEnabled(false);
        label1.setEnabled(false);
        idiot_label.setEnabled(false);
        bhagtosKayMujaraKar_label.setEnabled(true);
        seatType_combo.setEnabled(true);
        getmovie="Bhagtos Kay Mujara Kar";
    }//GEN-LAST:event_bhagtosKayMujaraKar_labelMouseClicked

    private void label1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_label1MouseMoved

    private void idiot_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiot_labelMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idiot_labelMouseMoved

    private void rockstar_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockstar_labelMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rockstar_labelMouseMoved

    private void bhagtosKayMujaraKar_labelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhagtosKayMujaraKar_labelMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bhagtosKayMujaraKar_labelMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void seatNo_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatNo_comboActionPerformed
        // TODO add your handling code here:
       
        if(seatNo_combo.getSelectedItem().equals("Select No. Of Seats"))
        {
            seatNo_label.setText("");
            food_combo.setEnabled(false);
            foodNo_combo.setEnabled(false);
        }
        else if(seatType_combo.getSelectedItem().equals("Platinum - Rs.200"))
        {
            food_combo.setEnabled(true);
            seatno=Integer.parseInt(seatNo_combo.getSelectedItem().toString());
            seatPrice=(200*seatno);
            seatNo_label.setText("RS."+seatPrice);
            gstAndGrossAmount();     
        }
        else if(seatType_combo.getSelectedItem().equals("Diamond - Rs.150"))
        {
            food_combo.setEnabled(true);
            seatno=Integer.parseInt(seatNo_combo.getSelectedItem().toString());
            seatPrice=(150*seatno);
            seatNo_label.setText("RS."+seatPrice);
            gstAndGrossAmount();
        }
        else if(seatType_combo.getSelectedItem().equals("Gold - Rs.100"))
        {
            food_combo.setEnabled(true);
            seatno=Integer.parseInt(seatNo_combo.getSelectedItem().toString());
            seatPrice=(100*seatno);
            seatNo_label.setText("RS."+seatPrice);
            gstAndGrossAmount();
        }
        else if(seatType_combo.getSelectedItem().equals("Silver - Rs.70"))
        {
            food_combo.setEnabled(true);
            seatno=Integer.parseInt(seatNo_combo.getSelectedItem().toString());
            seatPrice=(200*seatno);
            seatNo_label.setText("RS."+seatPrice);
            gstAndGrossAmount();
        }
    }//GEN-LAST:event_seatNo_comboActionPerformed

    private void food_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_comboActionPerformed
        // TODO add your handling code here:
        if(food_combo.getSelectedItem().equals("Select Food & Beverage"))
        {
            food_label.setText("");
            foodNo_combo.setEnabled(false);
        }
        else if(food_combo.getSelectedItem().equals("Samosa - Rs.100"))
        {
            food_label.setText("Rs.100");
            foodNo_combo.setEnabled(true);
            foodNo_combo.setSelectedItem("Select Food & Beverage Qauntity");
            foodNo_label.setText("");
            getfood=food_combo.getSelectedItem().toString();
        }
        else if(food_combo.getSelectedItem().equals("PopCorn - Rs.150"))
        {
            food_label.setText("Rs.150");
            foodNo_combo.setEnabled(true);
            foodNo_combo.setSelectedItem("Select Food & Beverage Qauntity");
            foodNo_label.setText("");
            getfood=food_combo.getSelectedItem().toString();
        }
        else if(food_combo.getSelectedItem().equals("Coke - Rs.160"))
        {
            food_label.setText("Rs.160");
            foodNo_combo.setEnabled(true);
            foodNo_combo.setSelectedItem("Select Food & Beverage Qauntity");
            foodNo_label.setText("");
            getfood=food_combo.getSelectedItem().toString();
        }
        else if(food_combo.getSelectedItem().equals("Samosa Coke Combo - Rs.260"))
        {
            food_label.setText("Rs.260");
            foodNo_combo.setEnabled(true);
            foodNo_combo.setSelectedItem("Select Food & Beverage Qauntity");
            foodNo_label.setText("");
            getfood=food_combo.getSelectedItem().toString();
        }
        else if(food_combo.getSelectedItem().equals("Samosa PopCorn Combo - Rs.250"))
        {
            food_label.setText("Rs.250");
            foodNo_combo.setEnabled(true);
            foodNo_combo.setSelectedItem("Select Food & Beverage Qauntity");
            foodNo_label.setText("");
            getfood=food_combo.getSelectedItem().toString();
        }
        
    }//GEN-LAST:event_food_comboActionPerformed

    private void foodNo_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodNo_comboActionPerformed
        // TODO add your handling code here:
        
        if(foodNo_combo.getSelectedItem().equals("Select Food & Beverage Quantity"))
        {
            
            foodNo_label.setText("");
//            gst_label.setText("");
//            grossAmount_label.setText("");
        }
        else if(food_combo.getSelectedItem().equals("Samosa - Rs.100"))
        {
            food=Integer.parseInt(foodNo_combo.getSelectedItem().toString());
            foodPrice=(100*food);
            foodNo_label.setText("Rs."+foodPrice);
            gstAndGrossAmount();
            
        }
        else if(food_combo.getSelectedItem().equals("PopCorn - Rs.150"))
        {
            food=Integer.parseInt(foodNo_combo.getSelectedItem().toString());
            foodPrice=(150*food);
            foodNo_label.setText("Rs."+foodPrice);
            gstAndGrossAmount();
        }
        else if(food_combo.getSelectedItem().equals("Coke - Rs.160"))
        {
            food=Integer.parseInt(foodNo_combo.getSelectedItem().toString());
            foodPrice=(160*food);
            foodNo_label.setText("Rs."+foodPrice);
            gstAndGrossAmount();
        }
        else if(food_combo.getSelectedItem().equals("Samosa Coke Combo - Rs.260"))
        {
            food=Integer.parseInt(foodNo_combo.getSelectedItem().toString());
            foodPrice=(260*food);
            foodNo_label.setText("Rs."+foodPrice);
            gstAndGrossAmount();
        }
        else if(food_combo.getSelectedItem().equals("Samosa PopCorn Combo - Rs.250"))
        {
            food=Integer.parseInt(foodNo_combo.getSelectedItem().toString());
            foodPrice=(250*food);
            foodNo_label.setText("Rs."+foodPrice);
            gstAndGrossAmount();
        }
        

    }//GEN-LAST:event_foodNo_comboActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new UserLogin().show();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_buttonActionPerformed
        // TODO add your handling code here:
        newButton();
    }//GEN-LAST:event_new_buttonActionPerformed

    private void payment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_buttonActionPerformed
        // TODO add your handling code here:
        if(seatType_combo.getSelectedItem().equals("Select Seat Type"))
        {
            JOptionPane.showMessageDialog(null, "Select Seat Type");
        }
        else if(seatNo_combo.getSelectedItem().equals("Select No. Of Seats"))
        {
            JOptionPane.showMessageDialog(null, "Select No. Of Seats");
        }
        else if(food_combo.getSelectedItem().equals("Select Food & Beverage"))
        {
            JOptionPane.showMessageDialog(null, "Select Food & Beverage");
        }
        else if(foodNo_combo.getSelectedItem().equals("Select Food & Beverage Quantity"))
        {
            JOptionPane.showMessageDialog(null, "Select Food & Beverage Quantity");
        }
        else
            new PaymentSuccessful(getmovie, getseat, getfood, food, seatno, total).show();
    }//GEN-LAST:event_payment_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBookingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBookingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBookingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBookingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBookingWindow("","","",0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bhagtosKayMujaraKar_label;
    private javax.swing.JButton cancel_button;
    private javax.swing.JComboBox<String> foodNo_combo;
    private javax.swing.JLabel foodNo_label;
    private javax.swing.JComboBox<String> food_combo;
    private javax.swing.JLabel food_label;
    private javax.swing.JLabel grossAmount_label;
    private javax.swing.JLabel gst_label;
    private javax.swing.JLabel idiot_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label1;
    private javax.swing.JButton new_button;
    private javax.swing.JButton payment_button;
    private javax.swing.JLabel rockstar_label;
    private javax.swing.JComboBox<String> seatNo_combo;
    private javax.swing.JLabel seatNo_label;
    private javax.swing.JComboBox<String> seatType_combo;
    private javax.swing.JLabel seatType_label;
    // End of variables declaration//GEN-END:variables
}
